/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Oauth.h"

bool_t
xdr_request_authorization_args (XDR *xdrs, request_authorization_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->auto_renew))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_auth_res (XDR *xdrs, request_auth_res *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_request_token_args (XDR *xdrs, approve_request_token_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SignedData (XDR *xdrs, SignedData *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->files_and_perms, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_request_token_res (XDR *xdrs, approve_request_token_res *objp)
{
	register int32_t *buf;

	 if (!xdr_SignedData (xdrs, &objp->signed_data))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->is_signed))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_args (XDR *xdrs, request_access_token_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, ~0))
		 return FALSE;
	 if (!xdr_SignedData (xdrs, &objp->signed_data))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->is_signed))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_res (XDR *xdrs, request_access_token_res *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valability))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_args (XDR *xdrs, validate_delegated_action_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->op_type, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_access_token_res (XDR *xdrs, refresh_access_token_res *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->error, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->availability))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_access_token_args (XDR *xdrs, refresh_access_token_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	return TRUE;
}
