/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "Oauth.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

request_auth_res *
request_authorization_1(request_authorization_args *argp, CLIENT *clnt)
{
	static request_auth_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_authorization,
		(xdrproc_t) xdr_request_authorization_args, (caddr_t) argp,
		(xdrproc_t) xdr_request_auth_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

approve_request_token_res *
approve_request_token_1(approve_request_token_args *argp, CLIENT *clnt)
{
	static approve_request_token_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, approve_request_token,
		(xdrproc_t) xdr_approve_request_token_args, (caddr_t) argp,
		(xdrproc_t) xdr_approve_request_token_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

request_access_token_res *
request_access_token_1(request_access_token_args *argp, CLIENT *clnt)
{
	static request_access_token_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_access_token,
		(xdrproc_t) xdr_request_access_token_args, (caddr_t) argp,
		(xdrproc_t) xdr_request_access_token_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

char **
validate_delegated_action_1(validate_delegated_action_args *argp, CLIENT *clnt)
{
	static char *clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, validate_delegated_action,
		(xdrproc_t) xdr_validate_delegated_action_args, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

refresh_access_token_res *
refresh_access_token_1(refresh_access_token_args *argp, CLIENT *clnt)
{
	static refresh_access_token_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, refresh_access_token,
		(xdrproc_t) xdr_refresh_access_token_args, (caddr_t) argp,
		(xdrproc_t) xdr_refresh_access_token_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
